"""SYNTHETIC mockloop: build the scratch project used by docs/validation/mockloop.md.

    PYTHONPATH=<repo> python docs/validation/mockloop/build_scratch.py <scratch_root>

Creates (never touches the real presets/joshuamagazine):
  <root>/shortkit.root, presets/joshuamagazine (copy of the repo preset, still PROVISIONAL),
  assets/test/generated -> repo symlink, assets/fonts -> repo symlink, warehouse/ (empty),
  assets/library/music (music_bed_b = true track, music_bed_a = distractor, index.yaml),
  assets/library/sfx (gain/EQ variants of the generated SFX = the "user's" SFX library),
  assets/test/sources/{face_voice,people_voice}.mp4 (Intel CC-BY clips + espeak-ng TTS lines),
  presets/mocktruth (preset_id mocktruth-v1: the KNOWN ground-truth style),
  episodes/mockref-00{1..5}/plan.yaml (test mode, rendered with the mocktruth preset).

Everything produced here is SYNTHETIC: the "reference channel" is our own renderer driven by the
mocktruth preset.  Caption lines were written after looking at 1-fps contact sheets and gridded
full-resolution frames of the two Intel clips (observations in OBS below); the dialogue lines are
TTS lines we placed into the sources ourselves (not the on-screen people's speech).
"""
from __future__ import annotations

import copy
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[3]
GEN = REPO / "assets" / "test" / "generated"

# what the two Intel clips show (seen on 1-fps contact sheets + gridded frames, source px 768x432, 12 fps)
OBS = {
    "people": ["1.0-7.0 한 여성이 화면 아래에서 들어와 오른쪽 창가 벽 쪽으로 걸어가 7.0 에 사라짐",
               "8-14 빈 방", "15.0-20.5 두 사람(검은 옷, 파란 셔츠)이 아래에서 들어와 왼쪽 창 쪽으로 걸어가 20.5 에 사라짐",
               "21-27 빈 방", "28.0-35.0 세 사람이 아래에서 들어와 한 명은 왼쪽, 두 명은 오른쪽으로 흩어져 나감",
               "36-42 빈 방", "43.0-47.5 모자 쓴 남성이 아래에서 들어와 왼쪽으로 걸어 나감"],
    "face": ["0-3 빈 복도", "4.0-8.0 파란 티셔츠 남성이 카메라 쪽으로 걸어옴", "8.0-18.5 남성이 카메라 정면을 보고 서 있음",
             "19-27 빈 복도", "28.0-34.0 여성과 조끼 입은 남성이 나란히 걸어옴", "34.0-42.5 두 사람이 나란히 서 있음(여성 왼쪽)",
             "43.0 남성이 먼저 화면 밖으로 나감", "55.0-60.0 세 사람이 걸어옴", "60.0-66.5 세 사람이 서 있음(가운데 안경 쓴 남성)",
             "67-68 떠남", "75.0-79.0 긴 머리 여성이 걸어옴", "79.0-85.5 여성이 서 있음", "86 사라짐"],
}


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def ff(*args) -> None:
    subprocess.run(["ffmpeg", "-hide_banner", "-nostdin", "-v", "error", "-y", *map(str, args)], check=True)


def dump(p: Path, data, header: str = "") -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    txt = yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=140)
    p.write_text(header + txt, encoding="utf-8")


# ============================================================================ scratch root
def make_root(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    shutil.copy(REPO / "shortkit.root", root / "shortkit.root")
    for d in ("presets", "assets/test", "assets/library/music", "assets/library/sfx", "assets/test/sources", "warehouse",
              "episodes"):
        (root / d).mkdir(parents=True, exist_ok=True)
    pj = root / "presets" / "joshuamagazine"
    if not pj.exists():
        shutil.copytree(REPO / "presets" / "joshuamagazine", pj)
    for link, target in (("assets/test/generated", GEN), ("assets/fonts", REPO / "assets" / "fonts")):
        lp = root / link
        if not lp.is_symlink():
            if lp.exists():
                shutil.rmtree(lp)
            lp.symlink_to(target)
    # music library: the true track + a distractor
    md = root / "assets/library/music"
    for f in ("music_bed_b.wav", "music_bed_a.wav"):
        if not (md / f).exists():
            shutil.copy(GEN / f, md / f)
    dump(md / "index.yaml", {"tracks": [
        {"track_id": "bed_b_original", "song_id": "bed_b", "file": "music_bed_b.wav", "title": "Synthetic Bed B",
         "artist": "shortkit testassets synth", "version": "original", "tempo_ratio_to_original": 1.0,
         "license": "generated by shortkit (no third-party content)"},
        {"track_id": "bed_a_original", "song_id": "bed_a", "file": "music_bed_a.wav", "title": "Synthetic Bed A",
         "artist": "shortkit testassets synth", "version": "original", "tempo_ratio_to_original": 1.0,
         "license": "generated by shortkit (no third-party content)"}]},
        "# SYNTHETIC mockloop music library (scratch project only).\n"
        "# music_bed_b = the TRUE track of the synthetic mock references; music_bed_a = distractor.\n")
    # SFX library: gain/EQ variants of the generated SFX
    sd = root / "assets/library/sfx"
    for name, src, af in (("lib_pop_bright.wav", "pop", "volume=-4dB,equalizer=f=3000:t=q:w=1:g=3"),
                          ("lib_whoosh_soft.wav", "whoosh", "volume=-6dB,lowpass=f=6000"),
                          ("lib_ding_clean.wav", "ding", "volume=-3dB,highpass=f=300"),
                          ("lib_click_quiet.wav", "click", "volume=-5dB"),
                          ("lib_boing_eq.wav", "boing", "volume=-2dB,equalizer=f=500:t=q:w=1:g=-4"),
                          ("lib_boom_low.wav", "boom", "volume=-6dB")):
        if not (sd / name).exists():
            ff("-i", GEN / "sfx" / f"{src}.wav", "-af", af, "-fflags", "+bitexact", "-flags:a", "+bitexact", sd / name)
    # voice sources: silent Intel clips + TTS lines at known source times
    srcd = root / "assets/test/sources"
    for out, video, lines in (
            ("face_voice.mp4", "video/face-demographics-walking-and-pause.mp4",
             [("speech_01.wav", 10.0), ("speech_03.wav", 62.0)]),
            ("people_voice.mp4", "video/people-detection.mp4", [("speech_02.wav", 15.0)])):
        o = srcd / out
        if o.exists():
            continue
        dur = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0",
                                    str(GEN / video)], capture_output=True, text=True).stdout.strip())
        args = ["-i", GEN / video]
        parts, labels = [], []
        for i, (wav, at) in enumerate(lines):
            args += ["-i", GEN / wav]
            ms = int(round(at * 1000))
            parts.append(f"[{i + 1}:a]aresample=48000,adelay={ms}|{ms},apad,atrim=0:{dur:.6f}[s{i}]")
            labels.append(f"[s{i}]")
        mix = (";".join(parts) + ";" + "".join(labels) +
               f"amix=inputs={len(lines)}:normalize=0:duration=longest,aformat=channel_layouts=stereo[a]"
               if len(lines) > 1 else parts[0].replace("[s0]", ",aformat=channel_layouts=stereo[a]"))
        ff(*args, "-filter_complex", mix, "-map", "0:v", "-map", "[a]", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
           "-ar", "48000", "-fflags", "+bitexact", "-flags:a", "+bitexact", "-map_metadata", "-1", "-t", f"{dur:.6f}", o)
        (srcd / (out[:-4] + ".truth.json")).write_text(yaml.safe_dump({
            "schema": "shortkit.testsource/1", "synthetic": True, "video": f"assets/test/generated/{video}",
            "lines": [{"wav": f"assets/test/generated/{w}", "at_s": a} for w, a in lines],
            "note": "SYNTHETIC mockloop 소스: Intel 샘플(CC BY 4.0, 무음) 영상에 espeak-ng TTS 줄을 얹음. 화면 인물의 말이 아님."},
            allow_unicode=True), encoding="utf-8")


# ============================================================================ ground-truth preset
# Fonts: only faces the renderer can select are usable.  libass matches PostScript names only for CFF
# (OTF) faces, and shortkit.edit writes the PostScript name into the ASS style, so TrueType faces whose
# PostScript name is not also a family name (Black Han Sans, Do Hyeon, Jua, Gothic A1, Gugi, Sunflower,
# NanumSquare*) are refused by the render font guard (measured 2026-09-24, see mockloop.md).
TRUTH_ROLES = {
    "title": dict(font_name="NanumGothic ExtraBold", bold=True, size_px=96, color="#FFF3B0", highlight_color="#FF5A36",
                  outline_px=5, outline_color="#000000", box=dict(enabled=False, color="#000000", alpha=0.0, pad_x=18, pad_y=10),
                  line_spacing=1.12, max_width_px=1000, max_lines=2, max_chars_per_line=12,
                  anchor=dict(x=540, y=280, align="center", valign="middle"),
                  motion_in=dict(type="none", dur_s=0.0, scale_from=1.0, offset_px=0), motion_out=dict(type="none", dur_s=0.0),
                  timing=dict(lead_s=0.0, min_dur_s=1.0), persist="whole_video"),
    "description": dict(font_name="Pretendard Bold", bold=True, size_px=44, color="#CFE8FF", highlight_color="#FFE400",
                        outline_px=4, outline_color="#000000", box=dict(enabled=False, color="#000000", alpha=0.0, pad_x=14, pad_y=8),
                        line_spacing=1.15, max_width_px=980, max_lines=1, max_chars_per_line=20,
                        anchor=dict(x=540, y=430, align="center", valign="middle"),
                        motion_in=dict(type="fade", dur_s=0.25, scale_from=1.0, offset_px=0),
                        motion_out=dict(type="none", dur_s=0.0), timing=dict(lead_s=0.0, min_dur_s=2.0), persist="timed"),
    "situation": dict(font_name="Pretendard ExtraBold", bold=True, size_px=60, color="#FFFFFF", highlight_color="#FFE400",
                      outline_px=5, outline_color="#000000", box=dict(enabled=True, color="#000000", alpha=0.55, pad_x=18, pad_y=8),
                      line_spacing=1.2, max_width_px=960, max_lines=2, max_chars_per_line=16,
                      anchor=dict(x=540, y=1480, align="center", valign="middle"),
                      motion_in=dict(type="pop", dur_s=0.15, scale_from=0.8, offset_px=0),
                      motion_out=dict(type="none", dur_s=0.0), timing=dict(lead_s=0.0, min_dur_s=1.0), persist="timed"),
    "speaker": dict(font_name="Pretendard Bold", bold=True, size_px=38, color="#FFFFFF", highlight_color="#FFE400",
                    outline_px=0, outline_color="#000000", box=dict(enabled=True, color="#E6007E", alpha=0.85, pad_x=16, pad_y=6),
                    line_spacing=1.1, max_width_px=420, max_lines=1, max_chars_per_line=10,
                    anchor=dict(x=540, y=700, align="center", valign="middle"),
                    motion_in=dict(type="fade", dur_s=0.15, scale_from=1.0, offset_px=0),
                    motion_out=dict(type="fade", dur_s=0.15), timing=dict(lead_s=0.0, min_dur_s=1.0), persist="timed"),
    "dialogue": dict(font_name="Pretendard ExtraBold", bold=True, size_px=58, color="#9CFF57", highlight_color="#FFFFFF",
                     outline_px=5, outline_color="#000000", box=dict(enabled=False, color="#000000", alpha=0.0, pad_x=16, pad_y=8),
                     line_spacing=1.2, max_width_px=960, max_lines=2, max_chars_per_line=16,
                     anchor=dict(x=540, y=1480, align="center", valign="middle"),
                     motion_in=dict(type="none", dur_s=0.0, scale_from=1.0, offset_px=0),
                     motion_out=dict(type="none", dur_s=0.0), timing=dict(lead_s=0.0, min_dur_s=1.0),
                     quote_marks=["“", "”"], persist="timed"),
    "reaction": dict(font_name="Pretendard Black", bold=True, size_px=110, color="#FF4D4D", highlight_color="#FFFFFF",
                     outline_px=6, outline_color="#000000", box=dict(enabled=False, color="#000000", alpha=0.0, pad_x=16, pad_y=8),
                     line_spacing=1.1, max_width_px=900, max_lines=1, max_chars_per_line=8,
                     anchor=dict(x=540, y=1180, align="center", valign="middle"),
                     motion_in=dict(type="fade", dur_s=0.2, scale_from=1.0, offset_px=0),
                     motion_out=dict(type="fade", dur_s=0.2), timing=dict(lead_s=0.0, min_dur_s=0.6), persist="timed"),
}


def truth_preset(root: Path) -> dict:
    base = yaml.safe_load((REPO / "presets/joshuamagazine/preset.yaml").read_text(encoding="utf-8"))
    p = copy.deepcopy(base)
    p["preset_id"] = "mocktruth-v1"
    p["reference"].update({"platform": "synthetic", "channel_handle": "@mocktruth-synthetic",
                           "channel_url": "synthetic://mocktruth", "channel_id_hint": None,
                           "snapshot_file": "presets/mocktruth/reference/latest100.json"})
    p["canvas"].update({"width": 1080, "height": 1920, "fps": 30,
                        "background": {"type": "color", "color": "#14213D", "blur_sigma": 30},
                        "video_region": {"x": 0, "y": 620, "w": 1080, "h": 608, "fit": "cover"},
                        "safe_margin": {"left": 60, "right": 60, "top": 150, "bottom": 300}})
    for role, st in TRUTH_ROLES.items():
        r = p["text"]["roles"][role]
        r.update(copy.deepcopy(st))
        r["font_file"] = None
        r["shadow_px"] = 0
        r["shadow_color"] = "#000000"
        if role != "dialogue":
            r.pop("quote_marks", None)
    p["text"]["tone"].update({"register": "해요체", "sentence_end_examples": [], "emoji": False,
                              "notes": "SYNTHETIC mocktruth: 해요체로 쓴 모의 자막"})
    m = p["motion"]
    m["zoom"].update({"scale_to": 1.35, "dur_s": 0.4, "ease": "out", "recenter": False})
    m["freeze"].update({"hold_s": 0.5})
    m["transitions"].update({"default": "cut", "flash": {"dur_s": 0.16, "color": "#FFFFFF", "scope": "canvas"},
                             "crossfade": {"dur_s": 0.3}})
    m["speed"]["slowmo_factor"] = 0.5
    p["decorations"]["arrow"].update({"color": "#00E5FF", "size_px": 140, "outline_px": 5, "outline_color": "#1A1A1A",
                                      "blink_hz": 0.0, "head_len_ratio": 0.4, "head_width_ratio": 0.7,
                                      "shaft_width_ratio": 0.2})
    a = p["audio"]
    a["loudness"].update({"integrated_lufs": -15.0, "true_peak_db": -1.5})
    a["bgm"].update({"track_id": "bed_b_original", "title": "Synthetic Bed B", "version": "original", "tempo_ratio": 1.0,
                     "section_start_s": 5.0, "gain_db": -1.0, "fade_in_s": 0.0, "fade_out_s": 1.0, "loop": False})
    a["original"].update({"keep_gain_db": -2.0, "fade_s": 0.06})
    a["ducking"].update({"depth_db": 8.0, "attack_s": 0.1, "release_s": 0.35})
    a["sfx"].update({"catalog": "presets/mocktruth/sfx_catalog.json", "map": "presets/mocktruth/sfx_map.yaml",
                     "gain_db_default": -10.0})
    a["silence"]["fade_s"] = 0.08
    p["structure"]["formats_file"] = "presets/mocktruth/formats.yaml"
    p["structure"]["first_caption_at_s"] = 0.3
    p["identity_exclusions"]["logo_templates_dir"] = "presets/mocktruth/reference/identity_templates"
    return p


def write_truth_preset(root: Path) -> None:
    d = root / "presets" / "mocktruth"
    d.mkdir(parents=True, exist_ok=True)
    dump(d / "preset.yaml", truth_preset(root),
         "# SYNTHETIC GROUND TRUTH (mockloop) -- preset_id mocktruth-v1.\n"
         "# The style of the synthetic stand-in 'reference channel'. Never a measurement of any real channel.\n")
    dump(d / "formats.yaml", {"schema": "shortkit.formats/1", "preset_id": "mocktruth-v1", "status": "unmeasured",
                              "blocker": "SYNTHETIC truth preset: formats are not classified for the truth preset itself",
                              "table": [], "assignments": {}})
    (d / "sfx_catalog.json").write_text(
        '{"schema": "shortkit.sfx_catalog/1", "preset_id": "mocktruth-v1", "status": "unmeasured", '
        '"blocker": "SYNTHETIC truth preset: mocks use explicit SFX files", "types": []}\n', encoding="utf-8")
    dump(d / "sfx_map.yaml", {"schema": "shortkit.sfx_map/1", "preset_id": "mocktruth-v1",
                              "library_root": "assets/library/sfx", "library_status": "not_provided", "types": {}})
    dump(d / "requested_changes.yaml", {"preset_id": "mocktruth-v1", "changes": {}})


# ============================================================================ mock plans
A_ID, B_ID = "v_room", "v_hall"
A_PATH, B_PATH = "assets/test/sources/people_voice.mp4", "assets/test/sources/face_voice.mp4"
SFX = "assets/test/generated/sfx"
BGM = "assets/library/music/music_bed_b.wav"

PROTECT_A = [  # people_voice (768x432, from above): bodies of walking people, source time
    {"label": "들어오는 여성", "x": 300, "y": 80, "w": 170, "h": 270, "start": 1.0, "end": 3.5},
    {"label": "창가로 가는 여성", "x": 430, "y": 60, "w": 240, "h": 270, "start": 3.5, "end": 7.0},
    {"label": "왼쪽으로 가는 두 사람", "x": 60, "y": 80, "w": 350, "h": 310, "start": 15.0, "end": 20.5},
    {"label": "흩어지는 세 사람", "x": 150, "y": 80, "w": 500, "h": 352, "start": 28.0, "end": 35.0},
    {"label": "모자 쓴 남성", "x": 80, "y": 60, "w": 320, "h": 330, "start": 43.0, "end": 47.5},
]
PROTECT_B = [  # face_voice (768x432, frontal): faces, source time
    {"label": "걸어오는 남성 얼굴", "x": 320, "y": 100, "w": 130, "h": 150, "start": 4.0, "end": 8.0},
    {"label": "서 있는 남성 얼굴", "x": 320, "y": 90, "w": 130, "h": 145, "start": 8.0, "end": 18.5},
    {"label": "왼쪽 여성 얼굴", "x": 50, "y": 120, "w": 150, "h": 180, "start": 30.0, "end": 42.5},
    {"label": "조끼 남성 얼굴", "x": 440, "y": 40, "w": 130, "h": 160, "start": 30.0, "end": 43.5},
    {"label": "왼쪽 여성 얼굴(셋)", "x": 50, "y": 90, "w": 130, "h": 180, "start": 58.0, "end": 67.0},
    {"label": "가운데 남성 얼굴", "x": 300, "y": 80, "w": 120, "h": 150, "start": 58.0, "end": 67.0},
    {"label": "오른쪽 여성 얼굴", "x": 540, "y": 120, "w": 120, "h": 160, "start": 58.0, "end": 67.0},
    {"label": "긴 머리 여성 얼굴", "x": 280, "y": 10, "w": 130, "h": 200, "start": 77.0, "end": 86.0},
]


def sources(root: Path) -> list[dict]:
    out = []
    for sid, path, prot, note in ((A_ID, A_PATH, PROTECT_A, "people-detection + TTS speech_02 @15.0s"),
                                  (B_ID, B_PATH, PROTECT_B, "face-demographics + TTS speech_01 @10.0s, speech_03 @62.0s")):
        out.append({"id": sid, "path": path, "sha256": sha(root / path), "warehouse_id": None, "vocals_path": None,
                    "has_embedded_music": False,
                    "clean": {"crop": None, "delogo": [], "inpaint": [], "blur": []}, "protected": prot})
    return out


def cap(cid, role, text, start, end, src=None, src_t=None, kind="seen", note=None, pos=None, hl=None):
    c = {"id": cid, "role": role, "text": text, "start": round(float(start), 3), "end": round(float(end), 3)}
    if hl:
        c["highlight"] = list(hl)
    if pos is not None:
        c["pos"] = list(pos)
    if src is not None:
        g = {"kind": kind, "source": src, "src_t": src_t}
        if note:
            g["note"] = note
        c["grounding"] = g
    return c


def fx(fid, typ, t, desc, src, src_t, kind="action", ev_t=None):
    return {"id": fid, "type": typ, "t": t, "event": {"t": t if ev_t is None else ev_t, "desc": desc, "kind": kind,
                                                        "source": src, "src_t": src_t},
            "file": f"{SFX}/{typ}.wav"}


def arrow(did, start, end, x, y, reason, rotation=None):
    start, end = round(float(start), 3), round(float(end), 3)
    kf = {"t": 0.0, "x": x, "y": y}
    if rotation is not None:
        kf["rotation"] = rotation
    return {"id": did, "kind": "arrow", "start": start, "end": end, "keyframes": [kf], "reason": reason}


# per-episode natural variation of the positional / timing style values (truth = what each plan used)
VAR = {
    1: dict(title_y=280, desc_y=430, sit_y=1480, rx_y=1180, zoom=(1.35, 0.40), freeze=0.50, flash=0.16, xfade=None),
    2: dict(title_y=274, desc_y=426, sit_y=1486, rx_y=1176, zoom=(1.32, 0.36), freeze=0.45, flash=0.14, xfade=None),
    3: dict(title_y=284, desc_y=434, sit_y=1474, rx_y=1186, zoom=(1.38, 0.44), freeze=0.55, flash=0.18, xfade=0.25),
    4: dict(title_y=277, desc_y=430, sit_y=1483, rx_y=1180, zoom=(1.35, 0.40), freeze=0.50, flash=None, xfade=0.35),
    5: dict(title_y=286, desc_y=432, sit_y=1476, rx_y=1172, zoom=(1.30, 0.42), freeze=0.60, flash=0.16, xfade=None),
}
# Design rules (learned from the first mock round, see mockloop.md): consecutive segments come from DIFFERENT
# sources (a join of contiguous source time is invisible, so it is used only for the slow-motion ramps, which
# need a visible before/after inside one shot), freezes are placed MID-MOTION (a freeze of a still scene is
# indistinguishable from the scene), and 'cut' is the majority transition of every video.


class TL:
    """Output-time map of a timeline (same rules as shortkit.edit.resolve: crossfade overlaps the previous
    clip by dur; flash / cut do not; freeze at src_t inserts hold; freeze at end appends hold)."""

    def __init__(self, segs: list[dict]):
        self.segs = segs
        self.out: dict[str, tuple[float, float]] = {}
        t = 0.0
        for k, s in enumerate(segs):
            tr = s.get("transition_in") or {}
            if k and tr.get("type") == "crossfade":
                t -= float(tr["dur"])
            d = (s["src_out"] - s["src_in"]) / float(s.get("speed", 1.0))
            d += float((s.get("freeze") or {}).get("hold") or 0.0)
            self.out[s["id"]] = (round(t, 4), round(t + d, 4))
            t += d
        self.duration = round(t, 4)

    def o(self, sid: str, src_t: float) -> float:
        s = next(x for x in self.segs if x["id"] == sid)
        t = self.out[sid][0] + (src_t - s["src_in"]) / float(s.get("speed", 1.0))
        fz = s.get("freeze") or {}
        if fz.get("at") == "src_t" and src_t > fz["src_t"]:
            t += float(fz["hold"])
        return round(t, 3)


def plan_base(n: int, root: Path, title: str, notes: str) -> dict:
    return {"schema": "shortkit.plan/1", "episode_id": f"mockref-{n:03d}", "preset_id": "mocktruth-v1",
            "format_id": "UNCLASSIFIED", "mode": "test", "episode_index": 2,
            "notes": "SYNTHETIC mock reference (mockloop): 우리 렌더러 + mocktruth 프리셋으로 만든 가짜 레퍼런스. " + notes,
            "cover": {"text": title.replace("\n", " "), "frame_t": 0.0},
            "title_candidates": [title.replace("\n", " "), f"모의 레퍼런스 {n}", f"합성 {n}편"],
            "sources": sources(root)}


def seg(sid, src, a, b, purpose, **kw):
    d = {"id": sid, "source": src, "src_in": a, "src_out": b, "purpose": purpose}
    d.update(kw)
    return d


def keep(a, b, why="소스에 넣은 TTS 대사 한 줄을 살림(덕킹 검증용)"):
    return {"keep": True, "ranges": [[a, b]], "stem": "raw", "reason": why}


def plans(root: Path) -> dict[int, dict]:
    P = {}
    # ------------------------------------------------------------------ 001: A hook(zoom) | B flash | A dialogue | A slow | B freeze
    v = VAR[1]
    S = [540, v["sit_y"]]
    p = plan_base(1, root, "빈 방에 온 사람들", "hook(zoom)→flash 전개→대사→느린 재생(같은 샷)→정지 반응")
    tl = [seg("s1", A_ID, 1.0, 4.6, "hook", zoom={"center": [380, 200], "start": 0.8, "scale_to": v["zoom"][0],
                                                   "dur": v["zoom"][1], "reason": "걸어 들어오는 여성 확대"}),
          seg("s2", B_ID, 4.0, 9.0, "build", transition_in={"type": "flash", "dur": v["flash"]}),
          seg("s3", A_ID, 14.8, 17.8, "build", original_audio=keep(14.9, 17.2)),
          seg("s4", A_ID, 17.8, 19.3, "build", speed=0.5),
          seg("s5", B_ID, 29.0, 32.5, "reaction",
              freeze={"at": "src_t", "src_t": 31.0, "hold": v["freeze"], "reason": "다가오는 두 사람이 걷는 도중 멈춤"})]
    T = TL(tl)
    p["timeline"] = tl
    p["captions"] = [
        cap("c_title", "title", "빈 방에 온 사람들", 0.0, T.duration, pos=[540, v["title_y"]], hl=["사람들"]),
        cap("c_desc", "description", "복도와 빈 방의 이야기", 0.0, 3.4, pos=[540, v["desc_y"]]),
        cap("c_sit1", "situation", "한 여성이 방으로 들어와요", 0.3, 3.4, A_ID, 2.0, pos=S),
        cap("c_sit2", "situation", "남성이 카메라 쪽으로 와요", T.o("s2", 4.3), T.o("s2", 8.8), B_ID, 6.0, pos=S),
        cap("c_spk", "speaker", "파란 셔츠 남성", T.o("s2", 7.8), T.o("s2", 8.9), B_ID, 8.5, pos=[830, 800]),
        cap("c_dlg", "dialogue", "저기 봐, 들어온다!", T.o("s3", 15.0), T.o("s3", 17.15), A_ID, 15.0, kind="heard",
            note="소스에 얹은 TTS 한 줄(speech_02) — 화면 인물의 말이라고 주장하지 않음", pos=S),
        cap("c_sit3", "situation", "두 사람이 천천히 걸어가요", T.o("s4", 17.9), T.o("s4", 19.2), A_ID, 18.5, pos=S),
        cap("c_sit4", "situation", "두 사람이 나란히 다가와요", T.o("s5", 29.2), T.o("s5", 32.4), B_ID, 30.0, pos=S),
        cap("c_rx", "reaction", "멈칫", T.o("s5", 31.0) - 0.1, T.o("s5", 31.0) + 1.3, B_ID, 31.0, pos=[540, v["rx_y"]]),
    ]
    p["decorations"] = [arrow("d1", T.o("s2", 7.8), T.o("s2", 8.95), 540, 738, "멈춰 선 남성의 머리 위를 가리킴(얼굴 위쪽)")]
    p["sfx"] = [fx("fx1", "whoosh", 0.3, "여성이 화면 아래에서 들어옴", A_ID, 1.3),
                fx("fx2", "ding", T.o("s2", 8.0), "남성이 카메라 앞에 멈춰 섬", B_ID, 8.0),
                fx("fx3", "pop", T.o("s3", 15.2), "두 사람이 아래에서 들어옴", A_ID, 15.2),
                fx("fx4", "pop", T.o("s5", 31.0), "걷던 두 사람의 화면이 멈춤", B_ID, 31.0, kind="freeze")]
    p["bgm"] = {"enabled": True, "path": BGM, "silences": []}
    P[1] = p
    # ------------------------------------------------------------------ 002: B hook(zoom) | A freeze | B flash dialogue | A | A slow
    v = VAR[2]
    S = [540, v["sit_y"]]
    p = plan_base(2, root, "복도와 빈 방의\n방문자들", "hook(zoom)→걷는 중 정지→flash 대사→전개→느린 재생(같은 샷)")
    tl = [seg("s1", B_ID, 28.5, 33.0, "hook", zoom={"center": [500, 120], "start": 2.6, "scale_to": v["zoom"][0],
                                                     "dur": v["zoom"][1], "reason": "다가오는 조끼 남성 확대"},
              freeze={"at": "src_t", "src_t": 32.3, "hold": v["freeze"], "reason": "다가오는 두 사람이 걷는 도중 멈춤"}),
          seg("s2", A_ID, 28.0, 31.0, "build"),
          seg("s3", B_ID, 9.0, 12.8, "build", transition_in={"type": "flash", "dur": v["flash"]},
              original_audio=keep(9.9, 12.7)),
          seg("s4", A_ID, 43.0, 45.5, "build"),
          seg("s5", A_ID, 45.5, 47.0, "outro", speed=0.5)]
    T = TL(tl)
    p["timeline"] = tl
    p["cover"]["text"] = "복도와 빈 방의 방문자들"
    p["captions"] = [
        cap("c_title", "title", "복도와 빈 방의\n방문자들", 0.0, T.duration, pos=[540, v["title_y"]]),
        cap("c_desc", "description", "복도와 빈 방, 네 장면", 0.0, 3.8, pos=[540, v["desc_y"]]),
        cap("c_sit1", "situation", "두 사람이 나란히 걸어와요", 0.4, T.o("s1", 32.9), B_ID, 30.0, pos=S, hl=["나란히"]),
        cap("c_rx", "reaction", "멈칫", T.o("s1", 32.3) - 0.1, T.out["s1"][1] - 0.05, B_ID, 32.3, pos=[540, v["rx_y"]]),
        cap("c_sit2", "situation", "세 사람이 한꺼번에 들어와요", T.o("s2", 28.1), T.o("s2", 30.9), A_ID, 29.0, pos=S),
        cap("c_spk", "speaker", "파란 셔츠 남성", T.o("s3", 9.2), T.o("s3", 11.0), B_ID, 9.5, pos=[830, 800]),
        cap("c_dlg", "dialogue", "잠깐만요, 이거 진짜예요?", T.o("s3", 10.0), T.o("s3", 12.65), B_ID, 10.0, kind="heard",
            note="소스에 얹은 TTS 한 줄(speech_01)", pos=S),
        cap("c_sit3", "situation", "모자 쓴 남성이 지나가요", T.o("s4", 43.15), T.o("s4", 45.4), A_ID, 44.5, pos=S),
        cap("c_sit4", "situation", "천천히 화면 밖으로 나가요", T.o("s5", 45.6), T.o("s5", 46.95), A_ID, 46.5, pos=S),
    ]
    p["decorations"] = [arrow("d1", T.o("s3", 9.3), T.o("s3", 10.8), 540, 738, "서 있는 남성의 머리 위를 가리킴")]
    p["sfx"] = [fx("fx1", "whoosh", 0.4, "두 사람이 걸어 들어옴", B_ID, 28.9),
                fx("fx2", "pop", T.o("s1", 32.3), "다가오던 두 사람의 화면이 멈춤", B_ID, 32.3, kind="freeze"),
                fx("fx3", "ding", T.o("s4", 43.6), "모자 쓴 남성이 아래에서 들어옴", A_ID, 43.6),
                fx("fx4", "whoosh", T.o("s5", 46.8), "남성이 왼쪽 화면 밖으로 나감", A_ID, 46.8)]
    p["bgm"] = {"enabled": True, "path": BGM, "silences": []}
    P[2] = p
    # ------------------------------------------------------------------ 003: A hook(zoom) | B flash freeze | A | B xfade dialogue | A (+silence)
    v = VAR[3]
    S = [540, v["sit_y"]]
    p = plan_base(3, root, "세 사람의 등장", "hook(zoom)→flash 걷는 중 정지→전개→크로스페이드 대사→정적 뒤 마무리")
    tl = [seg("s1", A_ID, 28.0, 31.5, "hook", zoom={"center": [390, 250], "start": 1.0, "scale_to": v["zoom"][0],
                                                     "dur": v["zoom"][1], "reason": "들어오는 세 사람 확대"}),
          seg("s2", B_ID, 55.0, 58.5, "reaction", transition_in={"type": "flash", "dur": v["flash"]},
              freeze={"at": "src_t", "src_t": 57.5, "hold": v["freeze"], "reason": "다가오는 세 사람이 걷는 도중 멈춤"}),
          seg("s3", A_ID, 43.0, 46.5, "build"),
          seg("s4", B_ID, 60.5, 64.3, "build", transition_in={"type": "crossfade", "dur": v["xfade"]},
              original_audio=keep(61.9, 63.8)),
          seg("s5", A_ID, 1.0, 4.0, "outro")]
    T = TL(tl)
    p["timeline"] = tl
    p["captions"] = [
        cap("c_title", "title", "세 사람의 등장", 0.0, T.duration, pos=[540, v["title_y"]], hl=["등장"]),
        cap("c_desc", "description", "빈 방과 복도", 0.0, 3.3, pos=[540, v["desc_y"]]),
        cap("c_sit1", "situation", "세 사람이 한꺼번에 들어와요", 0.3, 3.3, A_ID, 29.0, pos=S),
        cap("c_sit2", "situation", "이번엔 복도로\n세 사람이 와요", T.o("s2", 55.1), T.o("s2", 58.4), B_ID, 56.5, pos=S),
        cap("c_rx", "reaction", "헉", T.o("s2", 57.5) - 0.1, T.o("s2", 57.5) + 1.3, B_ID, 57.5, pos=[540, v["rx_y"]]),
        cap("c_sit3", "situation", "모자 쓴 남성이 지나가요", T.o("s3", 43.2), T.o("s3", 46.3), A_ID, 45.0, pos=S, hl=["모자"]),
        cap("c_spk", "speaker", "가운데 남성", T.o("s4", 60.8), T.o("s4", 62.8), B_ID, 61.0, pos=[506, 692]),
        cap("c_dlg", "dialogue", "아니 이게 무슨 일이야", T.o("s4", 62.0), T.o("s4", 64.2), B_ID, 62.0, kind="heard",
            note="소스에 얹은 TTS 한 줄(speech_03)", pos=S),
        cap("c_sit4", "situation", "한 여성이 방으로 들어와요", T.o("s5", 1.2), T.o("s5", 3.9), A_ID, 2.5, pos=S),
    ]
    p["decorations"] = [arrow("d1", T.o("s4", 60.8), T.o("s4", 62.2), 935, 880,
                              "오른쪽 여성 쪽을 옆에서 가리킴(얼굴 오른쪽 바깥)", rotation=90.0)]
    p["sfx"] = [fx("fx1", "pop", 0.2, "세 사람이 아래에서 들어옴", A_ID, 28.2),
                fx("fx2", "pop", T.o("s2", 57.5), "다가오던 세 사람의 화면이 멈춤", B_ID, 57.5, kind="freeze"),
                fx("fx3", "ding", T.o("s3", 43.6), "모자 쓴 남성이 아래에서 들어옴", A_ID, 43.6)]
    sil0 = round(T.out["s5"][0] - 0.45, 3)
    p["bgm"] = {"enabled": True, "path": BGM,
                "silences": [{"start": sil0, "end": round(T.out["s5"][0] - 0.02, 3), "reason": "마지막 장면 직전 정적"}]}
    P[3] = p
    # ------------------------------------------------------------------ 004: B hook(zoom) | A | A slow | B freeze | A xfade (no dialogue)
    v = VAR[4]
    S = [540, v["sit_y"]]
    p = plan_base(4, root, "혼자 온 사람들", "hook(zoom)→전개→느린 재생(같은 샷)→걷는 중 정지→크로스페이드 마무리, 대사 없음")
    tl = [seg("s1", B_ID, 75.0, 79.0, "hook", zoom={"center": [340, 110], "start": 2.6, "scale_to": v["zoom"][0],
                                                     "dur": v["zoom"][1], "reason": "걸어오는 여성 확대"}),
          seg("s2", A_ID, 1.0, 3.5, "build"),
          seg("s3", A_ID, 3.5, 5.0, "build", speed=0.5),
          seg("s4", B_ID, 4.0, 7.5, "reaction",
              freeze={"at": "src_t", "src_t": 6.0, "hold": v["freeze"], "reason": "걸어오던 남성이 걷는 도중 멈춤"}),
          seg("s5", A_ID, 15.0, 18.5, "outro", transition_in={"type": "crossfade", "dur": v["xfade"]})]
    T = TL(tl)
    p["timeline"] = tl
    p["captions"] = [
        cap("c_title", "title", "혼자 온 사람들", 0.0, T.duration, pos=[540, v["title_y"]]),
        cap("c_desc", "description", "복도, 그리고 빈 방", 0.0, 3.6, pos=[540, v["desc_y"]]),
        cap("c_sit1", "situation", "한 여성이 복도로 걸어와요", 0.3, 3.9, B_ID, 77.0, pos=S),
        cap("c_sit2", "situation", "빈 방에도\n한 여성이 들어와요", T.o("s2", 1.2), T.o("s2", 3.4), A_ID, 2.0, pos=S),
        cap("c_sit3", "situation", "창가 쪽으로 천천히 가요", T.o("s3", 3.6), T.o("s3", 4.9), A_ID, 4.3, pos=S),
        cap("c_sit4", "situation", "남성이 카메라 쪽으로 와요", T.o("s4", 4.2), T.o("s4", 7.4), B_ID, 5.5, pos=S),
        cap("c_spk", "speaker", "파란 셔츠 남성", T.o("s4", 4.3), T.o("s4", 5.9), B_ID, 5.0, pos=[790, 800]),
        cap("c_rx", "reaction", "두근", T.o("s4", 6.0) - 0.1, T.o("s4", 6.0) + 1.3, B_ID, 6.0, pos=[540, v["rx_y"]]),
        cap("c_sit5", "situation", "두 사람이 왼쪽으로 가요", T.o("s5", 15.3), T.o("s5", 18.4), A_ID, 17.0, pos=S),
    ]
    p["decorations"] = [arrow("d1", T.o("s4", 6.0), T.o("s4", 6.0) + 0.5, 542, 752,
                              "멈춘 화면에서 남성의 머리 위를 가리킴")]
    p["sfx"] = [fx("fx1", "whoosh", 0.3, "여성이 복도 끝에서 나타남", B_ID, 75.3),
                fx("fx2", "ding", T.o("s2", 1.3), "여성이 아래에서 들어옴", A_ID, 1.3),
                fx("fx3", "pop", T.o("s3", 4.6), "여성이 창가에 다다름", A_ID, 4.6),
                fx("fx4", "pop", T.o("s4", 6.0), "걸어오던 남성의 화면이 멈춤", B_ID, 6.0, kind="freeze"),
                fx("fx5", "pop", T.o("s5", 15.3), "두 사람이 아래에서 들어옴", A_ID, 15.3)]
    p["bgm"] = {"enabled": True, "path": BGM, "silences": []}
    P[4] = p
    # ------------------------------------------------------------------ 005: B hook(zoom) | A freeze | B flash dialogue | A | A slow
    v = VAR[5]
    S = [540, v["sit_y"]]
    p = plan_base(5, root, "카메라 앞의 남성", "hook(zoom)→걷는 중 정지→flash 대사→전개→느린 재생(같은 샷)")
    tl = [seg("s1", B_ID, 3.5, 7.5, "hook", zoom={"center": [390, 160], "start": 2.8, "scale_to": v["zoom"][0],
                                                   "dur": v["zoom"][1], "reason": "다가오는 남성 얼굴 확대"},
              freeze={"at": "src_t", "src_t": 7.2, "hold": v["freeze"], "reason": "다가오는 남성이 걷는 도중 멈춤"}),
          seg("s2", A_ID, 28.0, 31.0, "build"),
          seg("s3", B_ID, 9.0, 12.8, "build", transition_in={"type": "flash", "dur": v["flash"]},
              original_audio=keep(9.9, 12.7)),
          seg("s4", A_ID, 15.0, 18.0, "build"),
          seg("s5", A_ID, 18.0, 20.0, "outro", speed=0.5)]
    T = TL(tl)
    p["timeline"] = tl
    p["captions"] = [
        cap("c_title", "title", "카메라 앞의 남성", 0.0, T.duration, pos=[540, v["title_y"]], hl=["남성"]),
        cap("c_desc", "description", "복도에서 생긴 일", 0.0, 3.8, pos=[540, v["desc_y"]]),
        cap("c_sit1", "situation", "한 남성이 걸어와요", 0.3, T.o("s1", 7.4), B_ID, 5.5, pos=S),
        cap("c_rx", "reaction", "스톱", T.o("s1", 7.2) - 0.1, T.out["s1"][1] - 0.05, B_ID, 7.2, pos=[540, v["rx_y"]]),
        cap("c_sit2", "situation", "세 사람이 한꺼번에 들어와요", T.o("s2", 28.2), T.o("s2", 30.9), A_ID, 29.0, pos=S),
        cap("c_spk", "speaker", "파란 셔츠 남성", T.o("s3", 9.2), T.o("s3", 10.8), B_ID, 9.5, pos=[830, 800]),
        cap("c_dlg", "dialogue", "잠깐만요, 이거 진짜예요?", T.o("s3", 10.0), T.o("s3", 12.65), B_ID, 10.0, kind="heard",
            note="소스에 얹은 TTS 한 줄(speech_01)", pos=S),
        cap("c_sit3", "situation", "두 사람이 왼쪽으로 가요", T.o("s4", 15.3), T.o("s4", 17.9), A_ID, 16.5, pos=S),
        cap("c_sit4", "situation", "천천히 사라져요", T.o("s5", 18.1), T.o("s5", 19.9), A_ID, 19.5, pos=S),
    ]
    p["decorations"] = [arrow("d1", T.o("s3", 9.3), T.o("s3", 10.6), 540, 738, "서 있는 남성의 머리 위를 가리킴")]
    p["sfx"] = [fx("fx1", "ding", T.o("s1", 6.5), "남성이 카메라 가까이 다가옴", B_ID, 6.5),
                fx("fx2", "pop", T.o("s1", 7.2), "다가오던 남성의 화면이 멈춤", B_ID, 7.2, kind="freeze"),
                fx("fx3", "whoosh", T.o("s4", 15.1), "두 사람이 아래에서 들어옴", A_ID, 15.1),
                fx("fx4", "pop", T.o("s5", 19.8), "두 사람이 왼쪽 벽 쪽으로 사라짐", A_ID, 19.8)]
    p["bgm"] = {"enabled": True, "path": BGM, "silences": []}
    P[5] = p
    return P


def write_plans(root: Path) -> None:
    for n, p in plans(root).items():
        d = root / "episodes" / p["episode_id"]
        dump(d / "plan.yaml", p, "# SYNTHETIC mock reference for the mockloop validation (docs/validation/mockloop.md).\n"
                                 "# Rendered with presets/mocktruth (preset_id mocktruth-v1). Not a real channel video.\n")


def main(argv: list[str]) -> int:
    root = Path(argv[1]).resolve() if len(argv) > 1 else Path(os.environ["SHORTKIT_ROOT"]).resolve()
    make_root(root)
    write_truth_preset(root)
    write_plans(root)
    print(f"SYNTHETIC mockloop scratch project ready: {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
