"""Preset loading, provenance registry, access tracing and the "no report-only settings" audit.

Layering (later wins)::

    presets/<name>/preset.yaml              base values (PROVISIONAL until measured)
    presets/<name>/measured.yaml            generated by `shortkit preset apply-measurements`
        common: {...}                       values measured over all formats
        by_format: {F1: {...}}              per-format measured values
    presets/<name>/requested_changes.yaml   user-requested changes (reported as intended changes)

Every *leaf* key of the effective preset has an entry in ``settings_registry.yaml`` linking
    evidence (video, time) -> measurement (n/p10/p50/p90, resolution) -> code (who reads it)
    -> QA checks (who verifies it in the output MP4).
``code`` is filled automatically from access traces (`Preset.get` records the caller) and
``qa_checks`` from the QA check declarations, so the registry cannot silently drift from the code.
"""
from __future__ import annotations

import copy
import fnmatch
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator, Mapping

from . import paths
from .util.jsonio import now_iso, read_json, read_yaml, write_json, write_yaml

MISSING = object()
_ABSENT = object()   # "not present" sentinel for lookups that must not raise

# Keys that are not reference measurements. value = category shown in the registry.
#   meta     : identification / bookkeeping
#   infra    : file locations / technical container settings
#   rule     : fixed by the user's production rules (not by the reference)
NON_MEASURED: dict[str, str] = {
    "preset_id": "meta",
    "schema": "meta",
    "reference.*": "meta",
    "per_episode": "meta",
    "identity_exclusions.forbidden_text": "rule",
    "identity_exclusions.logo_templates_dir": "infra",
    "identity_exclusions.own_branding": "rule",
    "approval.*": "rule",
    "text.font_dirs": "infra",
    "text.roles.*.font_file": "infra",
    "audio.sample_rate": "infra",
    "audio.sfx.catalog": "infra",
    "audio.sfx.map": "infra",
    "audio.sfx.max_event_offset_s": "rule",
    "audio.sfx.require_event": "rule",
    "audio.ducking.only_under_kept_dialogue": "rule",
    "audio.original.default": "rule",
    "audio.original.remove_embedded_music": "rule",
    "motion.zoom.max_consecutive": "rule",
    "motion.freeze.max_per_video": "rule",
    "motion.trim.tail_after_meaning_s": "rule",
    "structure.formats_file": "infra",
    "audio.loudness.tolerance_lu": "rule",
    "audio.loudness.max_limiter_db": "rule",
}

# What it costs production when a key stays unmeasured (못 잼). Pattern -> impact text.
IMPACT: dict[str, str] = {
    "canvas.*": "화면 비율·영상 영역·여백이 레퍼런스와 다를 수 있음 → 구도 불일치",
    "text.roles.*.font_name": "글꼴이 레퍼런스와 다를 수 있음 → 글자 인상·폭·줄바꿈 불일치",
    "text.roles.*.size_px": "글자 크기 불일치 → 줄 수·가림 영역 변화",
    "text.roles.*.anchor.*": "제목/자막 위치 불일치",
    "text.roles.*.outline*": "외곽선 두께·색 불일치",
    "text.roles.*.box.*": "자막 박스 유무·색·여백 불일치",
    "text.roles.*.motion_*": "자막 등장·퇴장 모션 불일치",
    "text.roles.*.timing.*": "자막 등장 타이밍 불일치",
    "text.roles.*.color": "글자 색 불일치",
    "text.roles.*.highlight_color": "강조 색 불일치",
    "text.tone.*": "자막 말투가 레퍼런스와 다를 수 있음",
    "motion.*": "확대·정지·전환의 크기/길이 불일치",
    "decorations.*": "화살표·원 등 장식 스타일 불일치",
    "audio.bgm.*": "BGM 곡/버전/속도/구간/크기 불일치 → 음악 일치 판정 불가",
    "audio.ducking.*": "보존 대사 구간의 BGM 덕킹 깊이·속도 불일치",
    "audio.loudness.*": "최종 음량 불일치",
    "render.clean.*": "원본 정리(흐림) 강도가 달라 가린 영역이 더/덜 보일 수 있음",
    "audio.original.keep_gain_db": "보존 원음 크기 불일치",
    "audio.original.fade_s": "원음 켜고 끄는 경계 처리 불일치",
    "audio.sfx.gain_db_default": "효과음 크기 불일치",
    "audio.silence.*": "의도적 정적 처리 불일치",
    "structure.*": "영상 길이·전개 구조 불일치",
    "cover.*": "표지 구성 불일치",
}


def _match(key: str, pattern: str) -> bool:
    return key == pattern or fnmatch.fnmatchcase(key, pattern)


def classify_key(key: str) -> str | None:
    for pat, cat in NON_MEASURED.items():
        if _match(key, pat):
            return cat
    return None


def impact_of(key: str) -> str:
    for pat, txt in IMPACT.items():
        if _match(key, pat):
            return txt
    return "레퍼런스와의 일치 여부를 판정할 수 없음"


def deep_merge(base: dict, over: Mapping | None) -> dict:
    out = copy.deepcopy(base)
    if not over:
        return out
    for k, v in over.items():
        if isinstance(v, Mapping) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = copy.deepcopy(v)
    return out


def flatten(d: Any, prefix: str = "") -> dict[str, Any]:
    """Leaf paths (dotted). Lists are leaves."""
    out: dict[str, Any] = {}
    if isinstance(d, Mapping):
        for k, v in d.items():
            p = f"{prefix}.{k}" if prefix else str(k)
            if isinstance(v, Mapping) and v:
                out.update(flatten(v, p))
            else:
                out[p] = v
    else:
        out[prefix] = d
    return out


def get_path(d: Mapping, key: str, default: Any = MISSING) -> Any:
    cur: Any = d
    for part in key.split("."):
        if isinstance(cur, Mapping) and part in cur:
            cur = cur[part]
        else:
            if default is MISSING:
                raise KeyError(key)
            return default
    return cur


# ----------------------------------------------------------------------------- access tracing
class AccessLog:
    def __init__(self) -> None:
        self.reads: dict[str, set[str]] = defaultdict(set)

    def record(self, key: str, caller: str) -> None:
        self.reads[key].add(caller)

    def to_dict(self) -> dict[str, list[str]]:
        return {k: sorted(v) for k, v in sorted(self.reads.items())}


def _caller() -> str:
    f = sys._getframe(2)
    here = Path(__file__).resolve()
    while f is not None and Path(f.f_code.co_filename).resolve() == here:
        f = f.f_back
    if f is None:
        return "?"
    fn = Path(f.f_code.co_filename)
    try:
        rel = paths.relp(fn)
    except Exception:
        rel = fn.name
    return f"{rel}:{f.f_code.co_name}"


class TrackedMapping(Mapping):
    """Read-only mapping view that records every leaf read with its caller."""

    def __init__(self, data: Mapping, prefix: str, log: AccessLog) -> None:
        self._d = data
        self._p = prefix
        self._log = log

    def _wrap(self, k: str, v: Any) -> Any:
        key = f"{self._p}.{k}" if self._p else k
        if isinstance(v, Mapping):
            return TrackedMapping(v, key, self._log)
        self._log.record(key, _caller())
        return v

    def __getitem__(self, k: str) -> Any:
        return self._wrap(k, self._d[k])

    def get(self, k: str, default: Any = None) -> Any:  # type: ignore[override]
        if k in self._d:
            return self._wrap(k, self._d[k])
        return default

    def __contains__(self, k: object) -> bool:  # membership test is not a value read
        return k in self._d

    def __iter__(self) -> Iterator[str]:
        return iter(self._d)

    def __len__(self) -> int:
        return len(self._d)

    def raw(self) -> dict:
        """Untracked deep copy (for serialization only -- do not use to read style values)."""
        return copy.deepcopy(dict(self._d))


@dataclass
class Preset:
    name: str                      # folder name under presets/
    data: dict                     # effective (merged) values
    base: dict
    measured: dict
    requested: dict
    format_id: str | None = None
    log: AccessLog = field(default_factory=AccessLog)

    @property
    def preset_id(self) -> str:
        return self.data["preset_id"]

    @property
    def dir(self) -> Path:
        return paths.preset_dir(self.name)

    def get(self, key: str, default: Any = MISSING) -> Any:
        v = get_path(self.data, key, default)
        if isinstance(v, Mapping):
            return TrackedMapping(v, key, self.log)
        self.log.record(key, _caller())
        return v

    def peek(self, key: str, default: Any = None) -> Any:
        """Untraced read for display only (reports, proposals). Never use it to drive production."""
        v = get_path(self.data, key, _ABSENT)
        return default if v is _ABSENT else copy.deepcopy(v)

    def section(self, key: str) -> TrackedMapping:
        v = get_path(self.data, key)
        if not isinstance(v, Mapping):
            raise TypeError(f"{key} is not a section")
        return TrackedMapping(v, key, self.log)

    def origin(self, key: str) -> str:
        """requested_change | measured | provisional | rule | infra | meta"""
        cat = classify_key(key)
        if get_path(self.requested.get("changes") or {}, key, _ABSENT) is not _ABSENT:
            return "requested_change"
        fmt_over = (self.measured.get("by_format") or {}).get(self.format_id or "", {}) or {}
        if get_path(fmt_over, key, _ABSENT) is not _ABSENT or \
                get_path(self.measured.get("common") or {}, key, _ABSENT) is not _ABSENT:
            return "measured"
        return cat or "provisional"

    def requested_keys(self) -> list[str]:
        return sorted(flatten(self.requested.get("changes") or {}).keys())

    def unmeasured_keys(self) -> list[str]:
        return sorted(k for k in flatten(self.data) if self.origin(k) == "provisional")

    def save_access_log(self, path: str | Path) -> None:
        write_json(path, {"preset_id": self.preset_id, "format_id": self.format_id, "saved_at": now_iso(),
                          "reads": self.log.to_dict()})

    def assert_same_preset(self, other_preset_id: str, what: str) -> None:
        """Guard against mixing presets from other projects into this channel."""
        if other_preset_id != self.preset_id:
            raise PresetMixError(f"{what} belongs to preset '{other_preset_id}', not '{self.preset_id}'. "
                                 "Presets must not be mixed.")


class PresetMixError(RuntimeError):
    pass


def load_preset(name: str, format_id: str | None = None) -> Preset:
    d = paths.preset_dir(name)
    base = read_yaml(d / "preset.yaml")
    if base is None:
        raise FileNotFoundError(d / "preset.yaml")
    measured = read_yaml(d / "measured.yaml", {}) or {}
    requested = read_yaml(d / "requested_changes.yaml", {}) or {}
    for layer, lname in ((measured, "measured.yaml"), (requested, "requested_changes.yaml")):
        pid = layer.get("preset_id")
        if pid and pid != base["preset_id"]:
            raise PresetMixError(f"{lname} is for preset '{pid}', not '{base['preset_id']}'")
    eff = deep_merge(base, measured.get("common"))
    if format_id:
        eff = deep_merge(eff, (measured.get("by_format") or {}).get(format_id))
    eff = deep_merge(eff, requested.get("changes"))
    return Preset(name=name, data=eff, base=base, measured=measured, requested=requested, format_id=format_id)


def preset_name_for_id(preset_id: str) -> str:
    root = paths.project_root() / "presets"
    for p in sorted(root.iterdir()):
        y = read_yaml(p / "preset.yaml")
        if y and y.get("preset_id") == preset_id:
            return p.name
    raise KeyError(f"no preset with preset_id={preset_id}")


# ----------------------------------------------------------------------------- registry
def registry_path(name: str) -> Path:
    return paths.preset_dir(name) / "settings_registry.yaml"


def sync_registry(name: str, access_logs: list[str | Path] | None = None,
                  qa_declarations: dict[str, list[str]] | None = None) -> dict:
    """(Re)build settings_registry.yaml from the preset layers, measurement files, access logs
    and QA check declarations.  Existing hand-written fields (evidence notes, resolution_state
    notes) are preserved."""
    pr = load_preset(name)
    reg_file = registry_path(name)
    old = (read_yaml(reg_file, {}) or {}).get("entries", {})
    meas_dir = pr.dir / "measurements"
    meas: dict[str, dict] = {}
    if meas_dir.is_dir():
        for f in sorted(meas_dir.glob("*.json")):
            m = read_json(f)
            items = m if isinstance(m, list) else m.get("items", [m]) if isinstance(m, dict) else []
            for it in items:
                if isinstance(it, dict) and it.get("key"):
                    it = dict(it)
                    it["file"] = paths.relp(f)
                    meas[it["key"]] = it
    code: dict[str, set[str]] = defaultdict(set)
    for lp in access_logs or []:
        lg = read_json(lp, {}) or {}
        if lg.get("preset_id") not in (None, pr.preset_id):
            continue
        for k, callers in (lg.get("reads") or {}).items():
            code[k].update(callers)
    if qa_declarations is None:
        qa_declarations = _qa_declarations()
    entries: dict[str, dict] = {}
    for key, value in flatten(pr.data).items():
        prev = old.get(key, {})
        cat = classify_key(key)
        origin = pr.origin(key)
        m = meas.get(key)
        if origin == "requested_change":
            status = "requested_change"
        elif m and m.get("status") == "measured":
            status = "measured"
        elif cat in ("meta", "infra"):
            status = "not_applicable"
        elif cat == "rule":
            status = "fixed_by_rule"
        else:
            status = "unmeasured"
        prev_code = set(prev.get("code") or [])
        e = {
            "scope": "fixed",
            "category": cat or "style",
            "status": status,
            "value": value,
            "value_origin": origin,
            "evidence": (m or {}).get("evidence") or prev.get("evidence") or [],
            "measurement": ({k: m.get(k) for k in ("file", "overall", "by_format", "resolution", "method",
                                                   "measured_at", "unit") if k in m} if m else None),
            "code": sorted(prev_code | code.get(key, set())),
            "qa_checks": sorted({cid for cid, pats in qa_declarations.items()
                                 if any(_match(key, p) for p in pats)}),
            "impact_if_unmeasured": impact_of(key) if status == "unmeasured" else None,
            "resolution_state": ("resolved" if status in ("measured", "requested_change", "fixed_by_rule",
                                                           "not_applicable")
                                 else prev.get("resolution_state") or "blocked_network"),
        }
        if m and m.get("status") != "measured" and m.get("blocker"):
            e["blocker"] = m["blocker"]
        entries[key] = e
    reg = {"schema": "shortkit.registry/1", "preset_id": pr.preset_id, "synced_at": now_iso(),
           "legend": {
               "status": {"measured": "레퍼런스에서 측정", "unmeasured": "못 잼(임시값 사용 중)",
                          "requested_change": "사용자 요청 변경", "fixed_by_rule": "사용자 제작 규칙으로 고정",
                          "not_applicable": "측정 대상 아님(메타/경로)"},
               "chain": "evidence(영상·시각) → measurement(n,p10,p50,p90,해상도) → code(읽는 함수) → qa_checks(출력 검사)"},
           "entries": entries}
    write_yaml(reg_file, reg)
    return reg


def _qa_declarations() -> dict[str, list[str]]:
    try:
        from .qa.checks import declarations  # type: ignore

        return declarations()
    except Exception:
        return {}


def audit(name: str, production: bool = True) -> dict:
    """Return problems that block production use of the preset.

    - style keys still unmeasured (못 잼)            -> blocks production (allowed in test mode)
    - style keys that no code reads (report-only)    -> always a defect
    - style keys that no QA check verifies           -> always a defect
    """
    reg = read_yaml(registry_path(name), {}) or {}
    problems = {"unmeasured": [], "no_code": [], "no_qa": []}
    for key, e in (reg.get("entries") or {}).items():
        if e.get("category") in ("meta", "infra"):
            continue
        if e.get("status") == "unmeasured":
            problems["unmeasured"].append(key)
        if not e.get("code"):
            problems["no_code"].append(key)
        if not e.get("qa_checks") and e.get("category") != "rule":
            problems["no_qa"].append(key)
    ok = not problems["no_code"] and not problems["no_qa"] and (not production or not problems["unmeasured"])
    return {"ok": ok, "production": production, **problems}
