"""`shortkit preset ...` : registry sync, audit, applying measurements."""
from __future__ import annotations

import argparse
import sys

from . import config, paths
from .util.jsonio import now_iso, read_json, read_yaml, write_yaml


def register(p: argparse.ArgumentParser) -> None:
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("sync", help="settings_registry.yaml 재생성(측정 파일·접근 기록·QA 선언 반영)")
    s.add_argument("--preset", default="joshuamagazine")
    s.add_argument("--access-log", action="append", default=[],
                   help="episodes/<id>/build/preset_access.json (여러 번 지정 가능). 생략 시 모든 에피소드에서 수집")
    s.set_defaults(func=cmd_sync)

    a = sub.add_parser("audit", help="보고서에만 있고 코드/검사에 연결되지 않은 설정, 미측정 설정 점검")
    a.add_argument("--preset", default="joshuamagazine")
    a.add_argument("--test", action="store_true", help="테스트 모드: 미측정 값은 경고로만 취급")
    a.set_defaults(func=cmd_audit)

    m = sub.add_parser("apply-measurements", help="measurements/*.json 의 측정값을 measured.yaml 로 반영")
    m.add_argument("--preset", default="joshuamagazine")
    m.set_defaults(func=cmd_apply)

    sh = sub.add_parser("show", help="유효 프리셋 값과 출처(measured/provisional/requested_change) 출력")
    sh.add_argument("--preset", default="joshuamagazine")
    sh.add_argument("--format", default=None)
    sh.add_argument("key", nargs="?", default=None)
    sh.set_defaults(func=cmd_show)


def _all_access_logs() -> list[str]:
    root = paths.project_root()
    return [str(p) for p in sorted(root.glob("episodes/*/build/preset_access.json"))]


def cmd_sync(args) -> int:
    logs = args.access_log or _all_access_logs()
    reg = config.sync_registry(args.preset, access_logs=logs)
    ents = reg["entries"]
    by = {}
    for e in ents.values():
        by[e["status"]] = by.get(e["status"], 0) + 1
    print(f"registry: {len(ents)} keys  " + "  ".join(f"{k}={v}" for k, v in sorted(by.items())))
    print(f"access logs used: {len(logs)}")
    return 0


def cmd_audit(args) -> int:
    res = config.audit(args.preset, production=not args.test)
    for k in ("unmeasured", "no_code", "no_qa"):
        print(f"{k}: {len(res[k])}")
        for key in res[k][:200]:
            print(f"   - {key}")
    print("RESULT:", "OK" if res["ok"] else "BLOCKED")
    return 0 if res["ok"] else 1


def apply_measurements(preset: str) -> dict:
    d = paths.preset_dir(preset)
    base = read_yaml(d / "preset.yaml")
    common: dict = {}
    by_format: dict = {}
    applied, skipped = [], []
    for f in sorted((d / "measurements").glob("*.json")):
        m = read_json(f)
        items = m.get("items", [m]) if isinstance(m, dict) else m
        for it in items:
            key = it.get("key")
            if not key:
                continue
            if it.get("status") != "measured" or it.get("value") is None:
                skipped.append(key)
                continue
            _set(common, key, it["value"])
            applied.append(key)
            for fmt, st in (it.get("by_format") or {}).items():
                if isinstance(st, dict) and st.get("value") is not None:
                    _set(by_format.setdefault(fmt, {}), key, st["value"])
    out = {"preset_id": base["preset_id"], "generated_at": now_iso(),
           "note": "generated by `shortkit preset apply-measurements`; do not edit by hand",
           "common": common, "by_format": by_format}
    write_yaml(d / "measured.yaml", out)
    return {"applied": applied, "skipped_unmeasured": skipped}


def _set(d: dict, dotted: str, value) -> None:
    parts = dotted.split(".")
    cur = d
    for p in parts[:-1]:
        cur = cur.setdefault(p, {})
    cur[parts[-1]] = value


def cmd_apply(args) -> int:
    r = apply_measurements(args.preset)
    print(f"applied {len(r['applied'])} measured keys; {len(r['skipped_unmeasured'])} still unmeasured")
    config.sync_registry(args.preset, access_logs=_all_access_logs())
    return 0


def cmd_show(args) -> int:
    pr = config.load_preset(args.preset, args.format)
    flat = config.flatten(pr.data)
    for k, v in flat.items():
        if args.key and not k.startswith(args.key):
            continue
        print(f"{k} = {v!r}   [{pr.origin(k)}]")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    register(ap)
    a = ap.parse_args()
    sys.exit(a.func(a))
